name: Deploy Order Service

on:
  push:
    branches: [ main ]
    paths: [ 'OrderService/**' ]
  workflow_dispatch:

env:
  ACR_NAME: ganeshfoodcourtmicroservices
  RESOURCE_GROUP: FoodCourt-RG
  APP_NAME: order-service-app
  IMAGE_BASE: ganeshfoodcourtmicroservices.azurecr.io/order-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: az acr login --name ${{ env.ACR_NAME }}
      - name: Build and Push
        run: |
          IMAGE_TAG=${{ env.IMAGE_BASE }}:${{ github.run_number }}
          docker build -t $IMAGE_TAG ./OrderService/OrderService
          docker push $IMAGE_TAG
      - name: Deploy
        run: |
          az containerapp update --name ${{ env.APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --image ${{ env.IMAGE_BASE }}:${{ github.run_number }}
          --min-replicas 1